apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system