apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 24h
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: 16.7.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 1Gi
    global:
      storageClass: longhorn
    postgresqlPassword: root
  install:
    createNamespace: true
