apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  namespace: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
