---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgC29MXILwu9BX8ML6xpvmhYwCuCot3b3S4rqLJcr3ucHh91hBgPe7jJ5JETOT2LIUbdRzJ7O02//ra05/3e+a61AtfbctT1nssuvqCdt5DSHZZwkju8DhK7FqDyBuYTOZXpmqD7i5ar/q60xsGuiiukN+V4LkfLLMuv97UG14Cr0HXqw2+vrhiS94+4HGhKXniLZhALAScgdVpKQvZ3qQB4YBMk7tTEynRE8KDKy3YEYSiJd0UQ53cMAP+x5ZFu5HTybu3JLoMKPMdt6QwicyyBTel03GH5ffisuzEwaTPmBg+NbQEABTwslC18I8DwT40nk+QLLlR4PFaAQpwXnYMm1ezpijmmLj3KYADFSsb5Q7rtRDVQ60EDdT7vNLJ49MSMfW60N/ta0pira51Rom3ILw7h/92Vmlng5iddOYq+sd/lWOxfRSgzwf64I/65jgNMbvaVM0k+1ULPpjUFQBXPZiC1NguoDKm5++gxibFh5skD455uT6Zf4QSKQboN8LuGXUWjI1i2hmbvcomhVIGbLpl0MTkxR1cdaXXaeAOyRYEfGm8SDMihRWcaQABcfdEh//jT6VjeAcChBV10neLaz2SXJrLr1pVHUTxa72d3PVwe+QEJho0XBHByjaqT3LT1HhGxUH60MBjViMwcktfHG8/m1xT6XdWwhCfrHF5Ar2wY+xhNn0/fYBRv7dglSrg7V6rMCUc7Las9O9ivsz3R
  template:
    metadata:
      creationTimestamp: null
      name: pg-secret
      namespace: postgres
    type: Opaque
